const symbolLibrary = {
	"ADM3": "Administration",
	"ADMD": "Administration",
	"AIRP": "Airport",
	"AIRF": "Airport",
	"Airport": "Airport",
	"AREA": "Area",
	"Area": "Area",
	"Bay": "Bay",
	"BAY": "Bay",
	"BCH": "Beach",
	"Beach": "Beach",
	"BDG": "Bridge",
	"Bridge": "Bridge",
	"BLDG": "Building",
	"BLDO": "Building",
	"Building": "Building",
	"CMPQ": "Camp",
	"CMP": "Camp",
	"CNL": "Canal",
	"Canal": "Canal",
	"CAPE": "Cape",
	"Cape": "Cape",
	"US Capitol": "Capitol",
	"CMTY": "Cemetery",
	"Cemetery":"Cemetery",
	"CHN": "Channel",
	"Channel": "Channel",
	"CH": "Church",
	"MSSNQ": "Church",
	"Church": "Church",
	"Civil": "Civil",
	"Crossing": "Crossing",
	"RDJCT": "Crossing",
	"DAM": "Dam",
	"Dam": "Dam",
	"Falls": "Falls",
	"OVF": "Falls",
	"FRMQ": "Farm",
	"FRM": "Farm",
	"Fire Station / EMS Station": "Firemen",
	"GDN": "Garden",
	"RECG": "Golf",
	"Gut": "Gut",
	"HBR": "Harbor",
	"Harbor": "Harbor",
	"AIRH": "Helipad",
	"HSP": "Hospital",
	"CTRM": "Hospital",
	"Hospital": "Hospital",
	"Hospital / Medical Center": "Hospital",
	"HTL": "Hotel",
	"ISL": "Island",
	"Island": "Island",
	"US Supreme Court": "Judge",
	"Court House": "Judge",
	"State Supreme Court": "Judge",
	"LK": "Lake",
	"Lake": "Lake",
	"LIBR": "Library",
	"ARCHV": "Library",
	"Locale": "Locale",
	"MALL": "Mall",
	"RET": "Mall",
	"Visitor / Information Center": "Map",
	"MAR": "Marina",
	"INSM": "Military",
	"MILB": "Military",
	"Military": "Military",
	"MNMT": "Monument",
	"MUS": "Museum",
	"Park": "Park",
	"PRK": "Park",
	"PKLT": "Parking Garage",
	"Picnic Area": "Picnic",
	"Pillar": "Pillar",
	"Law Enforcement": "Police",
	"Prison / Correctional Facility": "Police",
	"PPL": "Populated Place",
	"PPLX": "Populated Place",
	"Populated Place": "Populated Place",
	"PO": "Post Office",
	"Post Office": "Post Office",	
	"PS": "Power Substation",	
	"RSTN": "Rail Road",
	"RES": "Reserve",
	"Reserve": "Reserve",
	"RSV": "Reservoir",
	"Reservoir":"Reservoir",
	"REST": "Restaurant",
	"RD": "Road",
	"PPLQ": "Ruins",
	"HSTS": "Ruins",
	"SCH": "School",
	"ITTR": "School",
	"School": "School",
	"School: Elementary": "School",
	"School: High School": "School",
	"College / University": "School",
	"Technical / Trade School": "School",
	"School: Middle School": "School",
	"STNB": "School",
	"ATHF": "Soccer",
	"STDM": "Soccer",
	"SPNG": "Spring",
	"Spring": "Spring",
	"SQR": "Square",
	"STM": "Stream",
	"INLT": "Stream",
	"Stream": "Stream",
	"MT": "Summit",
	"Summit": "Summit",
	"THTR": "Theatre",
	"TOWR": "Tower",
	"Tower": "Tower",	
	"TRL": "Trail",
	"Trail": "Trail",	
	"MTRO": "Underground",	
	"VAL": "Valley",
	"Valley": "Valley",	
	"WHRF": "Wharf",	 
	"FRST": "Woods",
	"Woods": "Woods",
	"Unknown":"Unknown"
    }